### ISSUE TITLE
Disappearing Links

### ISSUE THREAD

**Issue by sajjadbashar** [d3/d3-sankey#41] opened 2017-07-27 15:07 UTC
I tried to create a perfectly rectangle sankey diagram by giving equal number for values in each layer, but it resulted in having the top and bottom rows of links disappeared. When I edit path curve points and round some numbers, they're revealed.
![screen shot 2017-07-27 at 11 07 15 am](https://user-images.githubusercontent.com/9739323/28677541-be9e129c-72bb-11e7-84f7-1213d8dbdefc.png)

**Comment by mbostock** [comment] 2017-07-27 15:56
Duplicate of #28.

**Closed by mbostock** 2017-07-27 15:56 UTC
