### ISSUE TITLE
Possible infinite loop in sankey generator

### ISSUE THREAD

**Issue by maferra** [d3/d3-sankey#50] opened 2018-01-06 10:51 UTC
I believe I have found an infinite loop behavior in the sankey generator. To reproduce it, I'm calling the sankey generator multiple times with different data (different nodes and links). If you could see the code that I have attached, the slider freezes when it reaches the year 2004 (actually, I don't know why 2004, the data is similar to all the others). The sankey function is called in line 22 of sankey_migration.js

Thank you for d3js and sankey.

[sankey_migration_infinite_loop.zip](https://github.com/d3/d3-sankey/files/1608706/sankey_migration_infinite_loop.zip)

**Comment by maferra** [comment] 2018-01-06 13:42
Yes, I believe I've found the problem, there's a circular reference on the links, going from 0 to 3 and 3 to 0.

```
{ "source": 0, "target": 3, "value": 63.16 },
{ "source": 3, "target": 0, "value": 14.099 }
```

So, the mistake it's on this side (now I have to think how to resolve it).
Everything should be fine with d3-sankey.

```
{
			"nodes": [
				{ "name": "Portugal" },
				{ "name": "Switzerland" },
				{ "name": "Germany" },
				{
					"name":
						"United Kingdom of Great Britain and Northern Ireland"
				},
				{ "name": "Luxembourg" },
				{ "name": "Belgium" },
				{ "name": "Cabo Verde" },
				{ "name": "Brazil" },
				{ "name": "Angola" },
				{ "name": "Guinea Bissau" }
			],
			"links": [
				{ "source": 0, "target": 1, "value": 135.449 },
				{ "source": 0, "target": 2, "value": 133.726 },
				{ "source": 0, "target": 3, "value": 63.16 },
				{ "source": 0, "target": 4, "value": 58.657 },
				{ "source": 0, "target": 5, "value": 25.636 },
				{ "source": 6, "target": 0, "value": 48.984 },
				{ "source": 7, "target": 0, "value": 23.921 },
				{ "source": 8, "target": 0, "value": 21.231 },
				{ "source": 9, "target": 0, "value": 16.375 },
				{ "source": 3, "target": 0, "value": 14.099 }
			]
		}
```

Best regards,

**Comment by mbostock** [comment] 2018-01-06 15:19
Duplicate of #1.

**Closed by mbostock** 2018-01-06 15:19 UTC
